// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuJPRiQJXHNYAME0LG5QU1taG7xr7zufc',
    appId: '1:5863588128:web:9a27a2db40e98ff00b1745',
    messagingSenderId: '5863588128',
    projectId: 'metamorphosis-66fd1',
    authDomain: 'metamorphosis-66fd1.firebaseapp.com',
    storageBucket: 'metamorphosis-66fd1.firebasestorage.app',
    measurementId: 'G-JCFM4YMSX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUihiqLl1BSZTFphc9tJtIttx7pRjhHds',
    appId: '1:5863588128:android:605fbe0341c0aec00b1745',
    messagingSenderId: '5863588128',
    projectId: 'metamorphosis-66fd1',
    storageBucket: 'metamorphosis-66fd1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLqfD-qb9NIfkpxoU2ACiGpW4DrESRaBg',
    appId: '1:5863588128:ios:de4436959b9fca720b1745',
    messagingSenderId: '5863588128',
    projectId: 'metamorphosis-66fd1',
    storageBucket: 'metamorphosis-66fd1.firebasestorage.app',
    iosBundleId: 'com.example.metamorphosis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLqfD-qb9NIfkpxoU2ACiGpW4DrESRaBg',
    appId: '1:5863588128:ios:de4436959b9fca720b1745',
    messagingSenderId: '5863588128',
    projectId: 'metamorphosis-66fd1',
    storageBucket: 'metamorphosis-66fd1.firebasestorage.app',
    iosBundleId: 'com.example.metamorphosis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuJPRiQJXHNYAME0LG5QU1taG7xr7zufc',
    appId: '1:5863588128:web:41493fc6865cecbf0b1745',
    messagingSenderId: '5863588128',
    projectId: 'metamorphosis-66fd1',
    authDomain: 'metamorphosis-66fd1.firebaseapp.com',
    storageBucket: 'metamorphosis-66fd1.firebasestorage.app',
    measurementId: 'G-2W4NKJFSGM',
  );
}
